### ISSUE TITLE
Bioluminescence blocked areas

### ISSUE THREAD

**Issue by Summonerd** [ReikaKalseki/Reika_FactorioMods_Issues#133]
There seem to be tiny patches of ground that can't be built on and show little red + symbols when hovered over with a building in hand. 
I believe these appear sometimes where modded trees are mined and they can only be removed by replacing the ground with waterfill and then landfill for example.

**Comment by ReikaKalseki** [comment]
I have already fixed this for the next release.

**Comment by Summonerd** [comment]
Hi, I'm still experiencing this bug with your latest release in 0.17x. When you said you fixed this for the next release, does that mean you're still waiting to release it?

**Comment by ReikaKalseki** [comment]
No, the 0.17 version is what the last 0.16 version was going to be.

That said, the 0.17 version of Bioluminescence has other issues and their fixes are likely to also solve this.

**Comment by shadoxxhd** [comment]
Are you planning to fix this for 0.16?

**Comment by ReikaKalseki** [comment]
No, I have already updated to 0.17.
