### ISSUE TITLE
Geothermal 1.17.1 crash on load

### ISSUE THREAD

**Issue by OvermindDL1** [ReikaKalseki/Reika_FactorioMods_Issues#138]
```lua
 536.288 Mods to disable:Failed to load mods: The given sprite rectangle (left_top=525x0, right_bottom=700x110) is outside the actual sprite size (left_top=0x0, right_bottom=624x141).
Sprite name: __Geothermal__/graphics/entity/chemical-plant/chemical-plant-shadow.png.: __Geothermal__/graphics/entity/chemical-plant/chemical-plant-shadow.png
```

**Comment by OvermindDL1** [comment]
And apparently the mod was updated 49 seconds ago.  ^.^

Updating and testing again, will close if that resolved it.

**Comment by OvermindDL1** [comment]
1.17.2 did not fix it:
```lua
 528.950 Mods to disable:Failed to load mods: The given sprite rectangle (left_top=525x0, right_bottom=700x110) is outside the actual sprite size (left_top=0x0, right_bottom=624x141).
Sprite name: __Geothermal__/graphics/entity/chemical-plant/chemical-plant-shadow.png.: __Geothermal__/graphics/entity/chemical-plant/chemical-plant-shadow.png
```

**Comment by iccor56** [comment]
i have the same issue

**Comment by ReikaKalseki** [comment]
It loads for me without issue:
![https://i.imgur.com/1fFUfLC.jpg](https://i.imgur.com/1fFUfLC.jpg)

That said, that *exact* format of error was initially thrown by a different Geothermal sprite, one which updating fixed.

**Comment by OvermindDL1** [comment]
Currently have `1.17.2` installed and it still throws that error when the mod is enabled on Factorio 0.17.17.

**Comment by N2O-Powered** [comment]
I also get this error, however it's also tagging the ["Squeak Through"](https://mods.factorio.com/mod/Squeak%20Through) mod. Maybe it's needed to throw this error?

**Comment by ghost** [comment]
Also get this exact same error on 1.17.2.

**Comment by CJagd** [comment]
I had the same problem and found something...  
Changing the "sprite resolution" from "normal" to "high" in the Graphics setting solve it !

**Comment by ghost** [comment]
> I had the same problem and found something...
> Changing the "sprite resolution" from "normal" to "high" in the Graphics setting solve it !

Unfortunately this isn't really playable for those of us running on a 1 GB video card (desktop is in need of repair, need my Factorio fix). :(
However, now that there's a lead, hopefully this will be resolved. :D

**Comment by ReikaKalseki** [comment]
> Changing the "sprite resolution" from "normal" to "high" in the Graphics setting solve it !

Well, that explains a lot, since I only play on High.

**Comment by OvermindDL1** [comment]
> Unfortunately this isn't really playable for those of us running on a 1 GB video card (desktop is in need of repair, need my Factorio fix). :(

Quite agree, 3 computers at my house and one has a 1GB GPU (the others are newer) and all play on normal resolution so they all match (people don't have to pick and choose because one looks better than the others).  Even attempting to set High then Factorio defaults it back to normal on the 1GB GPU so there is no capability to set it to high on this one.  Out of 201 mods in this pack, Geothermal is the only one with launching issues.

**Comment by ReikaKalseki** [comment]
Fixed.

**Comment by Sir-Jeffrey-Q** [comment]
I'm running into this same error on startup with 0.17.22, and 0.17.23. I tried the same fix of changing the sprite resolution to high, and while that seemed to fix it, it's also not ideal for my computer. Here's the error, if it helps.

"The given sprite rectangle (left_top=525x0, right_bottom=700x110) is outside the actualsprite size (left_top=0x0, right_bottom=624x141). Sprite name: __Geothermal__/graphics/entity/chemical-plant-shadow.png:__Geothermal__/graphics/entity/chemical-plant/chemical-plant-shadow.png"

**Comment by OvermindDL1** [comment]
Latest version published on Factorio Mods site as of this moment is still crashing on load.

**Comment by ReikaKalseki** [comment]
> Latest version published on Factorio Mods site as of this moment is still crashing on load.

"Fixed" and "released" are not synonyms.

**Comment by OvermindDL1** [comment]
Hmm, cloned https://github.com/ReikaKalseki/Geothermal.git as well and tested it and still the same issue.  Not seeing any further updated branches to test either (not seeing any branches at all actually).

Looking through the git commit log also shows no related changes to that code recently so it doesn't appear to be a committed fix yet?

**Comment by ReikaKalseki** [comment]
Fixed.
