### ISSUE TITLE
Error loading Dirty Mining

### ISSUE THREAD

**Issue by DonParpan** [ReikaKalseki/Reika_FactorioMods_Issues#164]
Startup error:
![image](https://user-images.githubusercontent.com/6019948/59142803-c77d0c80-89c3-11e9-9d52-a3cb713daec4.png)

**Comment by traiben** [comment]
problem with DirtyMining and the dirty_overlay icon, I fixed just scaling to sizes 64x64

**Comment by DonParpan** [comment]
Issue marked as fixed. Is not fixed for me, no update or anything like that.

**Comment by ReikaKalseki** [comment]
Fixed and released are not synonyms.
