### ISSUE TITLE
[End Game Combat] non-recoverable error (latest update)

### ISSUE THREAD

**Issue by Ideachan** [ReikaKalseki/Reika_FactorioMods_Issues#174]
Just updated to the latest version released like 17min ago but still having encountered the same error but with different error codes.
![image](https://user-images.githubusercontent.com/51479321/59624610-88487b80-917a-11e9-886f-6c2fde2c887a.png)

**Comment by barcharcraz** [comment]
I also experience this error

**Comment by ReikaKalseki** [comment]
I know I fixed this, and I looked at the code; it is the fixed version that would not generate the error you describe.

**Comment by numbernegative** [comment]
Also still getting this error. Can confirm running Endgame Combat version 1.17.12

**Comment by ReikaKalseki** [comment]
Are you using the latest version of Factorio?

**Comment by Ideachan** [comment]
Can confirm latest version as my steam setting for factorio is alway on (use the latest version available)

**Comment by ReikaKalseki** [comment]
I have tested and this does not happen for me. What situation does this error arise in?

**Comment by numbernegative** [comment]
Entering any game. Savefile or new game. As soon as you enter it pops up the error and kicks you back to the main menu.
Here's a log file from launching Factorio to crash at entering a save:
[factorio-current.log](https://github.com/ReikaKalseki/Reika_FactorioMods_Issues/files/3308429/factorio-current.log)

**Comment by ReikaKalseki** [comment]
I was doing that just *earlier today* without issue. Do you have other mods installed?

**Comment by Ideachan** [comment]
Yeah the few big ones I got are rampant arsenal, bob, angels and a bunch of subsidiary mods for these two mods.

**Comment by danielnichols** [comment]
I am also getting this issue. I have a bunch of mods installed, but even when I disable all except endgame combat and it's dependencies, I still get the error. Tried on both an existing world and a new game.

**Comment by Funketime** [comment]
I get this error exactly as listed here.  I have a new Factorio install on my laptop (0.17.50) running only Dragon Industries and Endgame Combat both at 1.17.12.  I have not changed the default setting and started a new game in default mode.  It also happens on my main computer, but that version has lots of other mods so I thought that I would try it in a clean install.

I have included my log file.
[factorio-current.log](https://github.com/ReikaKalseki/Reika_FactorioMods_Issues/files/3316485/factorio-current.log)

**Comment by Funketime** [comment]
I turned off the rotting flesh and did not get the error as it bypasses the function.  I looked at this line control.lua:
346 local invs = {defines.inventory.character_main, defines.inventory.character_quickbar, defines.inventory.character_vehicle}
In the Factorio API, I found the first and last defines, but could not find defines.inventory.character_quickbar so I removed it from the file and re-enable rotting flesh in the startup config and started a new game.  Again I did not get an error.  So I think the error is just a miss call to the API.

**Comment by ReikaKalseki** [comment]
> I turned of the rotting flesh 

See, this is the kind of information that is necessary, in this case that the crash only happens with a certain setting enabled.

**Comment by hanakocz** [comment]
Ok, my same crash was got by just downloading all reika's mods (except creative one and old wurm sounds), enabling them and entering the game. All settings should be default, so also this rotting flesh is enabled.

**Comment by Funketime** [comment]
Thinking overnight about this error, didn't they remove the quickbar inventory and turn it into a pointer to your main character inventory.  So it makes sense that when you look for alien flesh in your inventory, the quickbar search yields null.  I tested various configurations including adding flesh with and without rotting setup to see if there are other contributing factors.

The crash always happen if rotting flesh is turned on (with or without flesh in inventory) ,
the crash in not instant, but within a second,
the crash doesn't occur with rotting flesh turned off (with or without flesh in inventory),
the crash doesn't occur if line 346 removes the 'defines.inventory.character_quickbar' check.

**Comment by ReikaKalseki** [comment]
That is entirely correct, yes.

**Comment by ReikaKalseki** [comment]
Fixed.

**Comment by raiyuza** [comment]
Did this get released yet ? I am still getting the error while using latest experimental and endgame

**Comment by ReikaKalseki** [comment]
Check dates and see.
