### ISSUE TITLE
Loading error. using bobs mod and some small mods.

### ISSUE THREAD

**Issue by wubbel4** [ReikaKalseki/Reika_FactorioMods_Issues#179]
got this error while loading
![Knipsel](https://user-images.githubusercontent.com/52049583/59873734-f2406b00-939c-11e9-9848-61ca1e7d4e61.PNG)

**Comment by ReikaKalseki** [comment]
I have already fixed this.

**Comment by wubbel4** [comment]
still get the error when opening the game with the mod installed

**Comment by ReikaKalseki** [comment]
Fixed and released are not synonyms.

**Comment by wubbel4** [comment]
aha hahah my bad! love the mod though!
