### ISSUE TITLE
Nauvis Day: Incompatibity with AAI Industry

### ISSUE THREAD

**Issue by obj-obj** [ReikaKalseki/Reika_FactorioMods_Issues#271]
I waited a while for the previous error to be fixed and kind of forgot about it (I just played some other games), but just today I noticed something about this error: [https://github.com/ReikaKalseki/Reika_FactorioMods_Issues/issues/252](https://github.com/ReikaKalseki/Reika_FactorioMods_Issues/issues/252).

I checked through all my mods, and realized that the error only occurs when Nauvis Day is enabled together with Space Exploration. Would it be possible for you to fix this?

And I still can't figure out how to add tags, sorry.

**Comment by ReikaKalseki** [comment]
That issue already should be fixed.

**Comment by obj-obj** [comment]
I downloaded a clean install of factorio and installed nauvis day/space exploration, and the error is still happening.
But I realized that the incompatibility is specifically with one of the space exploration dependencies, AAI industry.

**Comment by ReikaKalseki** [comment]
Steam furnaces no longer clone smelting recipes, and instead just use the existing ones. They cannot possibly create some issue in the smelting system anymore.

**Comment by obj-obj** [comment]
I don’t know what the problem is then, it couldn’t be outdated mods because I downloaded a completely new install of factorio and installed both mods fresh. It couldn’t be a problem with the config either. 

Perhaps it is AAI industry that is the problem here instead of Nauvis Day

**Comment by ReikaKalseki** [comment]
I just looked at the code again, and there is no way in hell you are still getting that issue; line 81 of data-final-fixes is now manipulating technology effects, and the nearest mention of a "result" field is 30 lines away.

This is not a mod issue at all, AAI, NVDay, or otherwise; either you are still using an old copy of NVDay or you are claiming to have an issue you do not.

**Comment by obj-obj** [comment]
![image](https://user-images.githubusercontent.com/57120300/87583124-5876ea80-c690-11ea-9c96-455c74e07c60.png)
Well it's still happening
I should have checked this earlier, but the error is on a different line, probably was this whole time.
idk what's wrong, don't waste your time on this error anymore if no one else is having it

My installed version of nauvisday is 1.18.12, which is the same as the latest version on the factorio mods website.

Again, sorry that I didn't check for differences between this error and the last one, it's probably a different problem altogether from last time.

**Comment by obj-obj** [comment]
Well I'm just going to go through the code and try to fix it myself, even though I don't know anything about lua/modding

**Comment by ReikaKalseki** [comment]
At least line 20 mentions a result. And I think I know what is going on now. This would have been noticed and fixed two weeks ago with accurate information.

**Comment by obj-obj** [comment]
Entirely my fault. I just saw the same error and assumed it was on the same line.
