### ISSUE TITLE
Nauvis Day: Incompatibility with AAI Industry

### ISSUE THREAD

**Issue by obj-obj** [ReikaKalseki/Reika_FactorioMods_Issues#275]
There's another incompatibility, and I'll make sure to put all the relevant information here this time.

This occurred with the latest version of AAI Industry and Nauvis Day

Screenshot of error below:
![image](https://user-images.githubusercontent.com/57120300/89589615-d1361600-d7fa-11ea-96a7-8e27aef780c6.png)

**Comment by ReikaKalseki** [comment]
IronCartographer reported this the other day; it looks like AAI adds a refinery recipe with no ingredients.

**Comment by ReikaKalseki** [comment]
Fixed.

**Comment by obj-obj** [comment]
Thanks! Sorry I didn't notice this until now, my email notifications must not be working or something

**Comment by obj-obj** [comment]
![image](https://user-images.githubusercontent.com/57120300/90424195-904bc600-e072-11ea-8330-2e7ffd3a3202.png)
This is still happening, I assume it will be fixed in a later version?

**Comment by ReikaKalseki** [comment]
Fixed does not equal released.
