### ISSUE TITLE
Compatibilty

### ISSUE THREAD

**Issue by iDJHost** [ReikaKalseki/Reika_FactorioMods_Issues#7]
Appears to be an issue while trying to use with AAI Programmable Vehicles

![compatibility_issue](https://user-images.githubusercontent.com/21136403/29071697-640e203a-7c0a-11e7-88b9-9a41e1232eab.png)

**Comment by iDJHost** [comment]
Also an issue with Sulfur Mod maybe? 

![compatibility_issue2](https://user-images.githubusercontent.com/21136403/29071860-003560a4-7c0b-11e7-9c6a-ad81868d0ab0.png)

**Comment by iDJHost** [comment]
Also tin ore as previously stated by somebody else. I grew tired of toggling mods on and off. will check back after next update.

**Comment by ReikaKalseki** [comment]
An ore...projectile...?

> Also tin ore as previously stated by somebody else

What is the error? I can do nothing without specifics.

**Comment by ReikaKalseki** [comment]
I think I fixed the first two, and I suspect the tin issue as well in the process.

**Comment by iDJHost** [comment]
Even after the update, still getting the first error I posted with the AAI Programmable Vehicles - 

![compatibility_issue](https://user-images.githubusercontent.com/21136403/29121472-408a8584-7cd4-11e7-9e8e-8264220ee254.png)

**Comment by iDJHost** [comment]
Followed by a new error having to do with the thorium ore - 

![compatibility_issue3](https://user-images.githubusercontent.com/21136403/29121550-95205cfe-7cd4-11e7-8b0f-8366d6e561e9.png)

**Comment by ReikaKalseki** [comment]
I have added some debugging information to the next version. Try that.

**Comment by ReikaKalseki** [comment]
Any info?

**Comment by iDJHost** [comment]
Error's from start to finish disabling mods as needed to get game to load:

![error_01](https://user-images.githubusercontent.com/21136403/29240378-9fc3ccca-7f29-11e7-816d-42d08b472e0e.png)
![error_02](https://user-images.githubusercontent.com/21136403/29240389-be76bf38-7f29-11e7-895a-96ba3ecf2655.png)
![error_03](https://user-images.githubusercontent.com/21136403/29240395-d9a7d436-7f29-11e7-965b-75bf73174f09.png)

Game will now load, I can then toggle AAI Programmable Vehicles and Quarry back on and game works fine as if nothing changed.

**Comment by ReikaKalseki** [comment]
I need your log file, which contains the information.

**Comment by iDJHost** [comment]
what is the file location of the log file you need

**Comment by ReikaKalseki** [comment]
In your root game folder.

**Comment by Uriei** [comment]
I can upload mine if you want to, I'm having the same issue I'm also using Bob's Ores and Angel Infinite Ores.
[factorio-current.zip](https://github.com/ReikaKalseki/Reika_FactorioMods_Issues/files/1221657/factorio-current.zip)

**Comment by ReikaKalseki** [comment]
Try the new version.

**Comment by Uriei** [comment]
New version 1.0.8, same error, different ore. 
[factorio-current.zip](https://github.com/ReikaKalseki/Reika_FactorioMods_Issues/files/1222987/factorio-current.zip)

**Comment by ReikaKalseki** [comment]
And with 1.0.9?

**Comment by Uriei** [comment]
Nope with 1.0.9
![image](https://user-images.githubusercontent.com/6078221/29292785-c46702c4-8148-11e7-8133-d60fda09abdc.png)
[factorio-current.zip](https://github.com/ReikaKalseki/Reika_FactorioMods_Issues/files/1223526/factorio-current.zip)

**Comment by ReikaKalseki** [comment]
I am starting to think there is an error in whatever mod adds thorium ore, because it is looking like some of its core parameters are null. That said, try 1.0.10.

**Comment by Uriei** [comment]
I can tell you that if I disable Bob's Ores I can use DirtyMining, up to 1.0.9, because 1.0.10 doesn't even load with or without that one.
![image](https://user-images.githubusercontent.com/6078221/29297544-1d852106-8162-11e7-99cd-7a7ce5c83442.png)
[factorio-current.zip](https://github.com/ReikaKalseki/Reika_FactorioMods_Issues/files/1223817/factorio-current.zip)

**Comment by ReikaKalseki** [comment]
That one is a typo on my end. Try 1.0.11.

**Comment by Uriei** [comment]
Nope, still doesn't want to.
![image](https://user-images.githubusercontent.com/6078221/29297833-f08a0552-8163-11e7-8df3-1d6fba2abcc4.png)
[factorio-current.zip](https://github.com/ReikaKalseki/Reika_FactorioMods_Issues/files/1223835/factorio-current.zip)

**Comment by ReikaKalseki** [comment]
The error has at least moved, so this is progress. Try 1.0.12.

**Comment by Uriei** [comment]
I've just tried 1.0.12, it seems to work perfectly now, no errors and I created a new world and I see Bob's Ores with Angel's Infinite veins and I can set them to Dirty Mining without any problem. 

Good job ;)

**Comment by ReikaKalseki** [comment]
**Finally.**
