### ISSUE TITLE
Rampant arsenal questions

### ISSUE THREAD

**Issue by Silvernova115** [ReikaKalseki/Reika_FactorioMods_Issues#80]
how come these mods collide? 

37.787 Mods to disable:Failed to load mods: __EndgameCombat__/data-updates.lua:7: __EndgameCombat__/prototypes/rangeturrets.lua:114: Tech rampant-arsenal-technology-artillery-turret-damage-1 set to boost turret 'artillery-wagon', which does not exist! This is a bug in that mod!

is the bug similar to what you fixed recently but imbeded in rampant arsenal?

**Comment by ReikaKalseki** [comment]
I fixed this in the last release (101 or something like that).

**Comment by Silvernova115** [comment]
However I did update endgame to the recent version, the error still displays

**Comment by ReikaKalseki** [comment]
Fixed.
