### ISSUE TITLE
Nauvis Day error with Natural Evolution Enemies

### ISSUE THREAD

**Issue by Silvernova115** [ReikaKalseki/Reika_FactorioMods_Issues#81]
172.598 Error AtlasSystem.cpp:70: CheckSpriteRegistrationInsideSpritesheetArea should have caught this!: The given sprite position (left_top = 0x101) is completely outside the actual sprite image (size=113x91).
Sprite name: __NauvisDay__/graphics/entity/treefarm/dead-greenhouse-active.png
 172.632 Error AtlasSystem.cpp:1088: The given sprite position (left_top = 0x101) is completely outside the actual sprite image (size=113x91).
Sprite name: __NauvisDay__/graphics/entity/treefarm/dead-greenhouse-active.png
 172.690 Initial atlas bitmap size is 16384
 172.691 Created atlas bitmap 252x5 [none]
 172.691 Created atlas bitmap 132x24 [no-crop, trilinear-filtering, icon, light]
 172.869 Sprites loaded
 172.869 Convert atlas 132x24 to: trilinear-filtering 
 172.882 Warning ControlInput.cpp:270: Unknown control input string "CONTROL +T "
 172.883 Custom inputs active: 99
 172.886 Factorio initialised
 172.891 Mods to disable:Failed to load mods: The given sprite position (left_top = 0x101) is completely outside the actual sprite image (size=113x91).
Sprite name: __NauvisDay__/graphics/entity/treefarm/dead-greenhouse-active.png

mod interaction issue.

**Comment by Silvernova115** [comment]
still get the error without NEE so i dont know if its a bug or not

**Comment by ReikaKalseki** [comment]
This is already fixed in the most recent release.

**Comment by Silvernova115** [comment]
This error occured just now with the most recent version. this was not fixed.

**Comment by ReikaKalseki** [comment]
Ok, there is apparently something wrong with the mod portal's database - uploads are not taking effect.

**Comment by ReikaKalseki** [comment]
OK, I put in a more aggressive fix.
